/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import ActionGiftVariations from './model/ActionGiftVariations';
import AddressSuggestion from './model/AddressSuggestion';
import Attribute from './model/Attribute';
import AuthRequest from './model/AuthRequest';
import AuthResponse from './model/AuthResponse';
import AuthResponseAllOf from './model/AuthResponseAllOf';
import Banner from './model/Banner';
import BannerSlot from './model/BannerSlot';
import Branch from './model/Branch';
import Cafe from './model/Cafe';
import Cart from './model/Cart';
import CartAddItem from './model/CartAddItem';
import CartCompositeSelected from './model/CartCompositeSelected';
import CartIngredient from './model/CartIngredient';
import CartItem from './model/CartItem';
import CartMessage from './model/CartMessage';
import CartResult from './model/CartResult';
import CartStats from './model/CartStats';
import Category from './model/Category';
import CategoryProducts from './model/CategoryProducts';
import CompositeBlock from './model/CompositeBlock';
import Coordinates from './model/Coordinates';
import GiftVariation from './model/GiftVariation';
import GiftVariationBlock from './model/GiftVariationBlock';
import HouseAddress from './model/HouseAddress';
import Image from './model/Image';
import Ingredient from './model/Ingredient';
import MenuLink from './model/MenuLink';
import NewOrderRequest from './model/NewOrderRequest';
import NewOrderResult from './model/NewOrderResult';
import Order from './model/Order';
import Page from './model/Page';
import PaymentData from './model/PaymentData';
import PaymentMethod from './model/PaymentMethod';
import PingRes from './model/PingRes';
import Product from './model/Product';
import ProductSearchSuggest from './model/ProductSearchSuggest';
import ProductVariation from './model/ProductVariation';
import Profile from './model/Profile';
import ProfileAllOf from './model/ProfileAllOf';
import RegisterRequest from './model/RegisterRequest';
import RegisterSmsRequest from './model/RegisterSmsRequest';
import Result from './model/Result';
import SelectGiftRequest from './model/SelectGiftRequest';
import Seo from './model/Seo';
import ServerError from './model/ServerError';
import ValidationError from './model/ValidationError';
import DefaultApi from './api/DefaultApi';

/**
 * This_is_sionic_server.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var OpenApiCitypizza = require('index'); // See note below*.
 * var xxxSvc = new OpenApiCitypizza.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new OpenApiCitypizza.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new OpenApiCitypizza.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new OpenApiCitypizza.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 2.0.1
 */
export {
  /**
   * The ApiClient constructor.
   * @property {module:ApiClient}
   */
  ApiClient,
  /**
   * The ActionGiftVariations model constructor.
   * @property {module:model/ActionGiftVariations}
   */
  ActionGiftVariations,
  /**
   * The AddressSuggestion model constructor.
   * @property {module:model/AddressSuggestion}
   */
  AddressSuggestion,
  /**
   * The Attribute model constructor.
   * @property {module:model/Attribute}
   */
  Attribute,
  /**
   * The AuthRequest model constructor.
   * @property {module:model/AuthRequest}
   */
  AuthRequest,
  /**
   * The AuthResponse model constructor.
   * @property {module:model/AuthResponse}
   */
  AuthResponse,
  /**
   * The AuthResponseAllOf model constructor.
   * @property {module:model/AuthResponseAllOf}
   */
  AuthResponseAllOf,
  /**
   * The Banner model constructor.
   * @property {module:model/Banner}
   */
  Banner,
  /**
   * The BannerSlot model constructor.
   * @property {module:model/BannerSlot}
   */
  BannerSlot,
  /**
   * The Branch model constructor.
   * @property {module:model/Branch}
   */
  Branch,
  /**
   * The Cafe model constructor.
   * @property {module:model/Cafe}
   */
  Cafe,
  /**
   * The Cart model constructor.
   * @property {module:model/Cart}
   */
  Cart,
  /**
   * The CartAddItem model constructor.
   * @property {module:model/CartAddItem}
   */
  CartAddItem,
  /**
   * The CartCompositeSelected model constructor.
   * @property {module:model/CartCompositeSelected}
   */
  CartCompositeSelected,
  /**
   * The CartIngredient model constructor.
   * @property {module:model/CartIngredient}
   */
  CartIngredient,
  /**
   * The CartItem model constructor.
   * @property {module:model/CartItem}
   */
  CartItem,
  /**
   * The CartMessage model constructor.
   * @property {module:model/CartMessage}
   */
  CartMessage,
  /**
   * The CartResult model constructor.
   * @property {module:model/CartResult}
   */
  CartResult,
  /**
   * The CartStats model constructor.
   * @property {module:model/CartStats}
   */
  CartStats,
  /**
   * The Category model constructor.
   * @property {module:model/Category}
   */
  Category,
  /**
   * The CategoryProducts model constructor.
   * @property {module:model/CategoryProducts}
   */
  CategoryProducts,
  /**
   * The CompositeBlock model constructor.
   * @property {module:model/CompositeBlock}
   */
  CompositeBlock,
  /**
   * The Coordinates model constructor.
   * @property {module:model/Coordinates}
   */
  Coordinates,
  /**
   * The GiftVariation model constructor.
   * @property {module:model/GiftVariation}
   */
  GiftVariation,
  /**
   * The GiftVariationBlock model constructor.
   * @property {module:model/GiftVariationBlock}
   */
  GiftVariationBlock,
  /**
   * The HouseAddress model constructor.
   * @property {module:model/HouseAddress}
   */
  HouseAddress,
  /**
   * The Image model constructor.
   * @property {module:model/Image}
   */
  Image,
  /**
   * The Ingredient model constructor.
   * @property {module:model/Ingredient}
   */
  Ingredient,
  /**
   * The MenuLink model constructor.
   * @property {module:model/MenuLink}
   */
  MenuLink,
  /**
   * The NewOrderRequest model constructor.
   * @property {module:model/NewOrderRequest}
   */
  NewOrderRequest,
  /**
   * The NewOrderResult model constructor.
   * @property {module:model/NewOrderResult}
   */
  NewOrderResult,
  /**
   * The Order model constructor.
   * @property {module:model/Order}
   */
  Order,
  /**
   * The Page model constructor.
   * @property {module:model/Page}
   */
  Page,
  /**
   * The PaymentData model constructor.
   * @property {module:model/PaymentData}
   */
  PaymentData,
  /**
   * The PaymentMethod model constructor.
   * @property {module:model/PaymentMethod}
   */
  PaymentMethod,
  /**
   * The PingRes model constructor.
   * @property {module:model/PingRes}
   */
  PingRes,
  /**
   * The Product model constructor.
   * @property {module:model/Product}
   */
  Product,
  /**
   * The ProductSearchSuggest model constructor.
   * @property {module:model/ProductSearchSuggest}
   */
  ProductSearchSuggest,
  /**
   * The ProductVariation model constructor.
   * @property {module:model/ProductVariation}
   */
  ProductVariation,
  /**
   * The Profile model constructor.
   * @property {module:model/Profile}
   */
  Profile,
  /**
   * The ProfileAllOf model constructor.
   * @property {module:model/ProfileAllOf}
   */
  ProfileAllOf,
  /**
   * The RegisterRequest model constructor.
   * @property {module:model/RegisterRequest}
   */
  RegisterRequest,
  /**
   * The RegisterSmsRequest model constructor.
   * @property {module:model/RegisterSmsRequest}
   */
  RegisterSmsRequest,
  /**
   * The Result model constructor.
   * @property {module:model/Result}
   */
  Result,
  /**
   * The SelectGiftRequest model constructor.
   * @property {module:model/SelectGiftRequest}
   */
  SelectGiftRequest,
  /**
   * The Seo model constructor.
   * @property {module:model/Seo}
   */
  Seo,
  /**
   * The ServerError model constructor.
   * @property {module:model/ServerError}
   */
  ServerError,
  /**
   * The ValidationError model constructor.
   * @property {module:model/ValidationError}
   */
  ValidationError,
  /**
   * The DefaultApi service constructor.
   * @property {module:api/DefaultApi}
   */
  DefaultApi,
};
