/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddressSuggestion model module.
 * @module model/AddressSuggestion
 * @version 2.0.1
 */
class AddressSuggestion {
    /**
     * Constructs a new <code>AddressSuggestion</code>.
     * @alias module:model/AddressSuggestion
     * @param value {String} 
     * @param houseExists {Boolean} Ялвяется ли адрес точным с точностью до дома и валидным (присутствует в базе ФИАС)
     */
    constructor(value, houseExists) { 
        
        AddressSuggestion.initialize(this, value, houseExists);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value, houseExists) { 
        obj['value'] = value;
        obj['house_exists'] = houseExists;
    }

    /**
     * Constructs a <code>AddressSuggestion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddressSuggestion} obj Optional instance to populate.
     * @return {module:model/AddressSuggestion} The populated <code>AddressSuggestion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressSuggestion();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
            if (data.hasOwnProperty('house')) {
                obj['house'] = ApiClient.convertToType(data['house'], 'String');
            }
            if (data.hasOwnProperty('house_exists')) {
                obj['house_exists'] = ApiClient.convertToType(data['house_exists'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} value
 */
AddressSuggestion.prototype['value'] = undefined;

/**
 * @member {String} city
 */
AddressSuggestion.prototype['city'] = undefined;

/**
 * @member {String} street
 */
AddressSuggestion.prototype['street'] = undefined;

/**
 * @member {String} house
 */
AddressSuggestion.prototype['house'] = undefined;

/**
 * Ялвяется ли адрес точным с точностью до дома и валидным (присутствует в базе ФИАС)
 * @member {Boolean} house_exists
 */
AddressSuggestion.prototype['house_exists'] = undefined;






export default AddressSuggestion;

