/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthResponseAllOf model module.
 * @module model/AuthResponseAllOf
 * @version 2.0.1
 */
class AuthResponseAllOf {
    /**
     * Constructs a new <code>AuthResponseAllOf</code>.
     * @alias module:model/AuthResponseAllOf
     * @param emailConfirmed {Boolean} 
     */
    constructor(emailConfirmed) { 
        
        AuthResponseAllOf.initialize(this, emailConfirmed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, emailConfirmed) { 
        obj['email_confirmed'] = emailConfirmed;
    }

    /**
     * Constructs a <code>AuthResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthResponseAllOf} obj Optional instance to populate.
     * @return {module:model/AuthResponseAllOf} The populated <code>AuthResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthResponseAllOf();

            if (data.hasOwnProperty('email_confirmed')) {
                obj['email_confirmed'] = ApiClient.convertToType(data['email_confirmed'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} email_confirmed
 */
AuthResponseAllOf.prototype['email_confirmed'] = undefined;






export default AuthResponseAllOf;

