/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BannerSlot from './BannerSlot';

/**
 * The Banner model module.
 * @module model/Banner
 * @version 2.0.1
 */
class Banner {
    /**
     * Constructs a new <code>Banner</code>.
     * Набор баннеров
     * @alias module:model/Banner
     */
    constructor() { 
        
        Banner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Banner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Banner} obj Optional instance to populate.
     * @return {module:model/Banner} The populated <code>Banner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Banner();

            if (data.hasOwnProperty('is_mobile')) {
                obj['is_mobile'] = ApiClient.convertToType(data['is_mobile'], 'Boolean');
            }
            if (data.hasOwnProperty('slots')) {
                obj['slots'] = ApiClient.convertToType(data['slots'], [BannerSlot]);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} is_mobile
 */
Banner.prototype['is_mobile'] = undefined;

/**
 * @member {Array.<module:model/BannerSlot>} slots
 */
Banner.prototype['slots'] = undefined;






export default Banner;

