/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CartIngredient from './CartIngredient';

/**
 * The CartCompositeSelected model module.
 * @module model/CartCompositeSelected
 * @version 2.0.1
 */
class CartCompositeSelected {
    /**
     * Constructs a new <code>CartCompositeSelected</code>.
     * Выбранный товар в составе композитного
     * @alias module:model/CartCompositeSelected
     * @param productId {Number} 
     * @param variationId {Number} 
     */
    constructor(productId, variationId) { 
        
        CartCompositeSelected.initialize(this, productId, variationId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productId, variationId) { 
        obj['product_id'] = productId;
        obj['variation_id'] = variationId;
    }

    /**
     * Constructs a <code>CartCompositeSelected</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartCompositeSelected} obj Optional instance to populate.
     * @return {module:model/CartCompositeSelected} The populated <code>CartCompositeSelected</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartCompositeSelected();

            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
            }
            if (data.hasOwnProperty('variation_id')) {
                obj['variation_id'] = ApiClient.convertToType(data['variation_id'], 'Number');
            }
            if (data.hasOwnProperty('ingredients')) {
                obj['ingredients'] = ApiClient.convertToType(data['ingredients'], [CartIngredient]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} product_id
 */
CartCompositeSelected.prototype['product_id'] = undefined;

/**
 * @member {Number} variation_id
 */
CartCompositeSelected.prototype['variation_id'] = undefined;

/**
 * @member {Array.<module:model/CartIngredient>} ingredients
 */
CartCompositeSelected.prototype['ingredients'] = undefined;






export default CartCompositeSelected;

