/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CartResult model module.
 * @module model/CartResult
 * @version 2.0.1
 */
class CartResult {
    /**
     * Constructs a new <code>CartResult</code>.
     * @alias module:model/CartResult
     * @param ok {Boolean} 
     */
    constructor(ok) { 
        
        CartResult.initialize(this, ok);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ok) { 
        obj['ok'] = ok;
    }

    /**
     * Constructs a <code>CartResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartResult} obj Optional instance to populate.
     * @return {module:model/CartResult} The populated <code>CartResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartResult();

            if (data.hasOwnProperty('ok')) {
                obj['ok'] = ApiClient.convertToType(data['ok'], 'Boolean');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} ok
 */
CartResult.prototype['ok'] = undefined;

/**
 * @member {Array.<String>} errors
 */
CartResult.prototype['errors'] = undefined;






export default CartResult;

