/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CartCompositeSelected from './CartCompositeSelected';
import CartIngredient from './CartIngredient';

/**
 * The CartAddItem model module.
 * @module model/CartAddItem
 * @version 2.0.1
 */
class CartAddItem {
    /**
     * Constructs a new <code>CartAddItem</code>.
     * null
     * @alias module:model/CartAddItem
     * @param productId {Number} 
     * @param variationId {Number} 
     * @param quantity {Number} 
     */
    constructor(productId, variationId, quantity) { 
        
        CartAddItem.initialize(this, productId, variationId, quantity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productId, variationId, quantity) { 
        obj['product_id'] = productId;
        obj['variation_id'] = variationId;
        obj['quantity'] = quantity;
    }

    /**
     * Constructs a <code>CartAddItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartAddItem} obj Optional instance to populate.
     * @return {module:model/CartAddItem} The populated <code>CartAddItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartAddItem();

            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
            }
            if (data.hasOwnProperty('variation_id')) {
                obj['variation_id'] = ApiClient.convertToType(data['variation_id'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('ingredients')) {
                obj['ingredients'] = ApiClient.convertToType(data['ingredients'], [CartIngredient]);
            }
            if (data.hasOwnProperty('composite_selected')) {
                obj['composite_selected'] = ApiClient.convertToType(data['composite_selected'], [CartCompositeSelected]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} product_id
 */
CartAddItem.prototype['product_id'] = undefined;

/**
 * @member {Number} variation_id
 */
CartAddItem.prototype['variation_id'] = undefined;

/**
 * @member {Number} quantity
 */
CartAddItem.prototype['quantity'] = undefined;

/**
 * @member {Array.<module:model/CartIngredient>} ingredients
 */
CartAddItem.prototype['ingredients'] = undefined;

/**
 * @member {Array.<module:model/CartCompositeSelected>} composite_selected
 */
CartAddItem.prototype['composite_selected'] = undefined;






export default CartAddItem;

