/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CartStats model module.
 * @module model/CartStats
 * @version 2.0.1
 */
class CartStats {
    /**
     * Constructs a new <code>CartStats</code>.
     * null
     * @alias module:model/CartStats
     * @param count {Number} Кол-во товаров в корзине
     * @param sum {Number} Сумма корзины
     */
    constructor(count, sum) { 
        
        CartStats.initialize(this, count, sum);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count, sum) { 
        obj['count'] = count;
        obj['sum'] = sum;
    }

    /**
     * Constructs a <code>CartStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartStats} obj Optional instance to populate.
     * @return {module:model/CartStats} The populated <code>CartStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartStats();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('sum')) {
                obj['sum'] = ApiClient.convertToType(data['sum'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Кол-во товаров в корзине
 * @member {Number} count
 */
CartStats.prototype['count'] = undefined;

/**
 * Сумма корзины
 * @member {Number} sum
 */
CartStats.prototype['sum'] = undefined;






export default CartStats;

