/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Category from './Category';
import Product from './Product';

/**
 * The CategoryProducts model module.
 * @module model/CategoryProducts
 * @version 2.0.1
 */
class CategoryProducts {
    /**
     * Constructs a new <code>CategoryProducts</code>.
     * null
     * @alias module:model/CategoryProducts
     * @param category {module:model/Category} 
     * @param products {Array.<module:model/Product>} 
     */
    constructor(category, products) { 
        
        CategoryProducts.initialize(this, category, products);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, category, products) { 
        obj['category'] = category;
        obj['products'] = products;
    }

    /**
     * Constructs a <code>CategoryProducts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryProducts} obj Optional instance to populate.
     * @return {module:model/CategoryProducts} The populated <code>CategoryProducts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryProducts();

            if (data.hasOwnProperty('category')) {
                obj['category'] = Category.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [Product]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Category} category
 */
CategoryProducts.prototype['category'] = undefined;

/**
 * @member {Array.<module:model/Product>} products
 */
CategoryProducts.prototype['products'] = undefined;






export default CategoryProducts;

