/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Product from './Product';

/**
 * The CompositeBlock model module.
 * @module model/CompositeBlock
 * @version 2.0.1
 */
class CompositeBlock {
    /**
     * Constructs a new <code>CompositeBlock</code>.
     * null
     * @alias module:model/CompositeBlock
     * @param products {Array.<module:model/Product>} 
     */
    constructor(products) { 
        
        CompositeBlock.initialize(this, products);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, products) { 
        obj['products'] = products;
    }

    /**
     * Constructs a <code>CompositeBlock</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompositeBlock} obj Optional instance to populate.
     * @return {module:model/CompositeBlock} The populated <code>CompositeBlock</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompositeBlock();

            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [Product]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Product>} products
 */
CompositeBlock.prototype['products'] = undefined;






export default CompositeBlock;

