/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GiftVariation model module.
 * @module model/GiftVariation
 * @version 2.0.1
 */
class GiftVariation {
    /**
     * Constructs a new <code>GiftVariation</code>.
     * @alias module:model/GiftVariation
     * @param id {Number} 
     * @param variationId {Number} 
     * @param originalPrice {Number} 
     * @param price {Number} 
     * @param name {String} 
     * @param shortDescription {String} 
     * @param imageUrl {String} 
     */
    constructor(id, variationId, originalPrice, price, name, shortDescription, imageUrl) { 
        
        GiftVariation.initialize(this, id, variationId, originalPrice, price, name, shortDescription, imageUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, variationId, originalPrice, price, name, shortDescription, imageUrl) { 
        obj['id'] = id;
        obj['variation_id'] = variationId;
        obj['original_price'] = originalPrice;
        obj['price'] = price;
        obj['name'] = name;
        obj['short_description'] = shortDescription;
        obj['image_url'] = imageUrl;
    }

    /**
     * Constructs a <code>GiftVariation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GiftVariation} obj Optional instance to populate.
     * @return {module:model/GiftVariation} The populated <code>GiftVariation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GiftVariation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('variation_id')) {
                obj['variation_id'] = ApiClient.convertToType(data['variation_id'], 'Number');
            }
            if (data.hasOwnProperty('original_price')) {
                obj['original_price'] = ApiClient.convertToType(data['original_price'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('short_description')) {
                obj['short_description'] = ApiClient.convertToType(data['short_description'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GiftVariation.prototype['id'] = undefined;

/**
 * @member {Number} variation_id
 */
GiftVariation.prototype['variation_id'] = undefined;

/**
 * @member {Number} original_price
 */
GiftVariation.prototype['original_price'] = undefined;

/**
 * @member {Number} price
 */
GiftVariation.prototype['price'] = undefined;

/**
 * @member {String} name
 */
GiftVariation.prototype['name'] = undefined;

/**
 * @member {String} short_description
 */
GiftVariation.prototype['short_description'] = undefined;

/**
 * @member {String} image_url
 */
GiftVariation.prototype['image_url'] = undefined;






export default GiftVariation;

