/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GiftVariation from './GiftVariation';

/**
 * The GiftVariationBlock model module.
 * @module model/GiftVariationBlock
 * @version 2.0.1
 */
class GiftVariationBlock {
    /**
     * Constructs a new <code>GiftVariationBlock</code>.
     * Блок для выбора одного из подарков.
     * @alias module:model/GiftVariationBlock
     */
    constructor() { 
        
        GiftVariationBlock.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GiftVariationBlock</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GiftVariationBlock} obj Optional instance to populate.
     * @return {module:model/GiftVariationBlock} The populated <code>GiftVariationBlock</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GiftVariationBlock();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [GiftVariation]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/GiftVariation>} items
 */
GiftVariationBlock.prototype['items'] = undefined;






export default GiftVariationBlock;

