/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentData from './PaymentData';
import Profile from './Profile';

/**
 * The NewOrderRequest model module.
 * @module model/NewOrderRequest
 * @version 2.0.1
 */
class NewOrderRequest {
    /**
     * Constructs a new <code>NewOrderRequest</code>.
     * null
     * @alias module:model/NewOrderRequest
     * @param profile {module:model/Profile} 
     * @param payment {module:model/PaymentData} 
     */
    constructor(profile, payment) { 
        
        NewOrderRequest.initialize(this, profile, payment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, profile, payment) { 
        obj['profile'] = profile;
        obj['payment'] = payment;
    }

    /**
     * Constructs a <code>NewOrderRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewOrderRequest} obj Optional instance to populate.
     * @return {module:model/NewOrderRequest} The populated <code>NewOrderRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewOrderRequest();

            if (data.hasOwnProperty('profile')) {
                obj['profile'] = Profile.constructFromObject(data['profile']);
            }
            if (data.hasOwnProperty('payment')) {
                obj['payment'] = PaymentData.constructFromObject(data['payment']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Profile} profile
 */
NewOrderRequest.prototype['profile'] = undefined;

/**
 * @member {module:model/PaymentData} payment
 */
NewOrderRequest.prototype['payment'] = undefined;






export default NewOrderRequest;

