/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CartResult from './CartResult';
import Order from './Order';

/**
 * The NewOrderResult model module.
 * @module model/NewOrderResult
 * @version 2.0.1
 */
class NewOrderResult {
    /**
     * Constructs a new <code>NewOrderResult</code>.
     * null
     * @alias module:model/NewOrderResult
     * @param result {module:model/CartResult} 
     */
    constructor(result) { 
        
        NewOrderResult.initialize(this, result);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, result) { 
        obj['result'] = result;
    }

    /**
     * Constructs a <code>NewOrderResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewOrderResult} obj Optional instance to populate.
     * @return {module:model/NewOrderResult} The populated <code>NewOrderResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewOrderResult();

            if (data.hasOwnProperty('result')) {
                obj['result'] = CartResult.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = Order.constructFromObject(data['order']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CartResult} result
 */
NewOrderResult.prototype['result'] = undefined;

/**
 * @member {module:model/Order} order
 */
NewOrderResult.prototype['order'] = undefined;






export default NewOrderResult;

