/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Banner from './Banner';
import Cafe from './Cafe';
import Seo from './Seo';

/**
 * The Page model module.
 * @module model/Page
 * @version 2.0.1
 */
class Page {
    /**
     * Constructs a new <code>Page</code>.
     * Страница
     * @alias module:model/Page
     * @param id {Number} 
     * @param slug {String} 
     * @param name {String} 
     * @param parentId {Number} 
     * @param text {String} 
     * @param seo {module:model/Seo} 
     */
    constructor(id, slug, name, parentId, text, seo) { 
        
        Page.initialize(this, id, slug, name, parentId, text, seo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, slug, name, parentId, text, seo) { 
        obj['id'] = id;
        obj['slug'] = slug;
        obj['name'] = name;
        obj['parent_id'] = parentId;
        obj['text'] = text;
        obj['seo'] = seo;
    }

    /**
     * Constructs a <code>Page</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Page} obj Optional instance to populate.
     * @return {module:model/Page} The populated <code>Page</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Page();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('banners')) {
                obj['banners'] = ApiClient.convertToType(data['banners'], [Banner]);
            }
            if (data.hasOwnProperty('cafes')) {
                obj['cafes'] = ApiClient.convertToType(data['cafes'], [Cafe]);
            }
            if (data.hasOwnProperty('seo')) {
                obj['seo'] = Seo.constructFromObject(data['seo']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Page.prototype['id'] = undefined;

/**
 * @member {String} slug
 */
Page.prototype['slug'] = undefined;

/**
 * @member {String} name
 */
Page.prototype['name'] = undefined;

/**
 * @member {Number} parent_id
 */
Page.prototype['parent_id'] = undefined;

/**
 * @member {String} text
 */
Page.prototype['text'] = undefined;

/**
 * @member {Array.<module:model/Banner>} banners
 */
Page.prototype['banners'] = undefined;

/**
 * @member {Array.<module:model/Cafe>} cafes
 */
Page.prototype['cafes'] = undefined;

/**
 * @member {module:model/Seo} seo
 */
Page.prototype['seo'] = undefined;






export default Page;

