/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentMethod model module.
 * @module model/PaymentMethod
 * @version 2.0.1
 */
class PaymentMethod {
    /**
     * Constructs a new <code>PaymentMethod</code>.
     * Метод оплаты
     * @alias module:model/PaymentMethod
     * @param id {String} 
     * @param name {String} 
     * @param shortName {String} 
     */
    constructor(id, name, shortName) { 
        
        PaymentMethod.initialize(this, id, name, shortName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, shortName) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['short_name'] = shortName;
    }

    /**
     * Constructs a <code>PaymentMethod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentMethod} obj Optional instance to populate.
     * @return {module:model/PaymentMethod} The populated <code>PaymentMethod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentMethod();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('short_name')) {
                obj['short_name'] = ApiClient.convertToType(data['short_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PaymentMethod.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PaymentMethod.prototype['name'] = undefined;

/**
 * @member {String} short_name
 */
PaymentMethod.prototype['short_name'] = undefined;






export default PaymentMethod;

