/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PingRes model module.
 * @module model/PingRes
 * @version 2.0.1
 */
class PingRes {
    /**
     * Constructs a new <code>PingRes</code>.
     * @alias module:model/PingRes
     */
    constructor() { 
        
        PingRes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PingRes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PingRes} obj Optional instance to populate.
     * @return {module:model/PingRes} The populated <code>PingRes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PingRes();

            if (data.hasOwnProperty('hits')) {
                obj['hits'] = ApiClient.convertToType(data['hits'], 'Number');
            }
            if (data.hasOwnProperty('session')) {
                obj['session'] = ApiClient.convertToType(data['session'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} hits
 */
PingRes.prototype['hits'] = undefined;

/**
 * @member {String} session
 */
PingRes.prototype['session'] = undefined;






export default PingRes;

