/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductSearchSuggest model module.
 * @module model/ProductSearchSuggest
 * @version 2.0.1
 */
class ProductSearchSuggest {
    /**
     * Constructs a new <code>ProductSearchSuggest</code>.
     * @alias module:model/ProductSearchSuggest
     * @param id {Number} 
     * @param slug {String} 
     * @param name {String} 
     * @param imageUrl {String} 
     */
    constructor(id, slug, name, imageUrl) { 
        
        ProductSearchSuggest.initialize(this, id, slug, name, imageUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, slug, name, imageUrl) { 
        obj['id'] = id;
        obj['slug'] = slug;
        obj['name'] = name;
        obj['image_url'] = imageUrl;
    }

    /**
     * Constructs a <code>ProductSearchSuggest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductSearchSuggest} obj Optional instance to populate.
     * @return {module:model/ProductSearchSuggest} The populated <code>ProductSearchSuggest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductSearchSuggest();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('category_slug')) {
                obj['category_slug'] = ApiClient.convertToType(data['category_slug'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ProductSearchSuggest.prototype['id'] = undefined;

/**
 * @member {String} slug
 */
ProductSearchSuggest.prototype['slug'] = undefined;

/**
 * @member {String} name
 */
ProductSearchSuggest.prototype['name'] = undefined;

/**
 * @member {String} image_url
 */
ProductSearchSuggest.prototype['image_url'] = undefined;

/**
 * Для формирования ссылки на страницу товара
 * @member {String} category_slug
 */
ProductSearchSuggest.prototype['category_slug'] = undefined;






export default ProductSearchSuggest;

