/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisterSmsRequest model module.
 * @module model/RegisterSmsRequest
 * @version 2.0.1
 */
class RegisterSmsRequest {
    /**
     * Constructs a new <code>RegisterSmsRequest</code>.
     * @alias module:model/RegisterSmsRequest
     * @param phone {String} Формат \"9001112223\"
     * @param recaptchaResponse {String} Ответ от ReCaptcha
     */
    constructor(phone, recaptchaResponse) { 
        
        RegisterSmsRequest.initialize(this, phone, recaptchaResponse);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, recaptchaResponse) { 
        obj['phone'] = phone;
        obj['recaptcha_response'] = recaptchaResponse;
    }

    /**
     * Constructs a <code>RegisterSmsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterSmsRequest} obj Optional instance to populate.
     * @return {module:model/RegisterSmsRequest} The populated <code>RegisterSmsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterSmsRequest();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('recaptcha_response')) {
                obj['recaptcha_response'] = ApiClient.convertToType(data['recaptcha_response'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Формат \"9001112223\"
 * @member {String} phone
 */
RegisterSmsRequest.prototype['phone'] = undefined;

/**
 * Ответ от ReCaptcha
 * @member {String} recaptcha_response
 */
RegisterSmsRequest.prototype['recaptcha_response'] = undefined;






export default RegisterSmsRequest;

