/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisterRequest model module.
 * @module model/RegisterRequest
 * @version 2.0.1
 */
class RegisterRequest {
    /**
     * Constructs a new <code>RegisterRequest</code>.
     * @alias module:model/RegisterRequest
     * @param phone {String} Формат \"9001112223\"
     * @param smsCode {String} Код подтверждения из смс
     * @param email {String} 
     * @param password {String} 
     * @param phoneNotify {Boolean} Согласие на получение sms
     * @param emailNotify {Boolean} Согласие на получение email
     */
    constructor(phone, smsCode, email, password, phoneNotify, emailNotify) { 
        
        RegisterRequest.initialize(this, phone, smsCode, email, password, phoneNotify, emailNotify);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, smsCode, email, password, phoneNotify, emailNotify) { 
        obj['phone'] = phone;
        obj['sms_code'] = smsCode;
        obj['email'] = email;
        obj['password'] = password;
        obj['phone_notify'] = phoneNotify;
        obj['email_notify'] = emailNotify;
    }

    /**
     * Constructs a <code>RegisterRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterRequest} obj Optional instance to populate.
     * @return {module:model/RegisterRequest} The populated <code>RegisterRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterRequest();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('sms_code')) {
                obj['sms_code'] = ApiClient.convertToType(data['sms_code'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('phone_notify')) {
                obj['phone_notify'] = ApiClient.convertToType(data['phone_notify'], 'Boolean');
            }
            if (data.hasOwnProperty('email_notify')) {
                obj['email_notify'] = ApiClient.convertToType(data['email_notify'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Формат \"9001112223\"
 * @member {String} phone
 */
RegisterRequest.prototype['phone'] = undefined;

/**
 * Код подтверждения из смс
 * @member {String} sms_code
 */
RegisterRequest.prototype['sms_code'] = undefined;

/**
 * @member {String} email
 */
RegisterRequest.prototype['email'] = undefined;

/**
 * @member {String} password
 */
RegisterRequest.prototype['password'] = undefined;

/**
 * Согласие на получение sms
 * @member {Boolean} phone_notify
 */
RegisterRequest.prototype['phone_notify'] = undefined;

/**
 * Согласие на получение email
 * @member {Boolean} email_notify
 */
RegisterRequest.prototype['email_notify'] = undefined;






export default RegisterRequest;

