/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionGiftVariations from './ActionGiftVariations';

/**
 * The SelectGiftRequest model module.
 * @module model/SelectGiftRequest
 * @version 2.0.1
 */
class SelectGiftRequest {
    /**
     * Constructs a new <code>SelectGiftRequest</code>.
     * @alias module:model/SelectGiftRequest
     */
    constructor() { 
        
        SelectGiftRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SelectGiftRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SelectGiftRequest} obj Optional instance to populate.
     * @return {module:model/SelectGiftRequest} The populated <code>SelectGiftRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SelectGiftRequest();

            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], [ActionGiftVariations]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ActionGiftVariations>} actions
 */
SelectGiftRequest.prototype['actions'] = undefined;






export default SelectGiftRequest;

