/**
 * OpenAPI citypizza
 * This is sionic server
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Seo model module.
 * @module model/Seo
 * @version 2.0.1
 */
class Seo {
    /**
     * Constructs a new <code>Seo</code>.
     * SEO поля
     * @alias module:model/Seo
     * @param title {String} 
     * @param keywords {String} 
     * @param description {String} 
     */
    constructor(title, keywords, description) { 
        
        Seo.initialize(this, title, keywords, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, keywords, description) { 
        obj['title'] = title;
        obj['keywords'] = keywords;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>Seo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Seo} obj Optional instance to populate.
     * @return {module:model/Seo} The populated <code>Seo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Seo();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = ApiClient.convertToType(data['keywords'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
Seo.prototype['title'] = undefined;

/**
 * @member {String} keywords
 */
Seo.prototype['keywords'] = undefined;

/**
 * @member {String} description
 */
Seo.prototype['description'] = undefined;






export default Seo;

